# Generated by Django 4.2.1 on 2023-05-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('Faible', 'Faible'), ('Moyenne', 'Moyenne'), ('Élevée', 'Élevée')], max_length=128),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('À faire', 'A Faire'), ('En cours', 'En Cours'), ('Terminé', 'Terminé')], max_length=128),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Amélioration', 'Amélioration'), ('Tâche', 'Tâche')], max_length=128),
        ),
    ]
