# Generated by Django 4.2.1 on 2023-05-22 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contributors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=2048)),
                ('type', models.CharField(max_length=128)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_authored', to=settings.AUTH_USER_MODEL)),
                ('contributors', models.ManyToManyField(related_name='projects', through='contributors.Contributor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
