# Generated by Django 4.2.1 on 2023-05-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('Rôle 1', 'Role 1'), ('Rôle 2', 'Role 2'), ('Rôle 3', 'Role 3')], default='Supermission', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contributor',
            name='role',
            field=models.CharField(default='Rôle 1', max_length=128),
            preserve_default=False,
        ),
    ]
