# Generated by Django 4.2.1 on 2023-05-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0003_contributor_permission_contributor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('Permission niveau 1', 'Perm 1'), ('Permission niveau 2', 'Perm 2'), ('Permission niveau 3', 'Perm 3')], max_length=128),
        ),
    ]
